export enum EOrdersStatus {
    CONFIRMATION = 'CONFIRMATION',
    IN_PREPARATION = 'IN_PREPARATION',
    READY_DELIVERY = 'READY_DELIVERY',
    SENT_DELIVERY = 'SENT_DELIVERY',
    DELIVERED = 'DELIVERED',
    CANCEL = 'CANCEL',
  }
  